import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './Components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#F5F5F5]'>
          <Nav />
          {children}
        </body>
    </html>
  )
}
